### PR TITLE
Changes to be compatible with phpBB 3.1/3.2

### PR DESCRIPTION
**Pull request by ZetaTwo**
In 3.1 they changed two things:

- Post/topic count was split into multiple columns depending on status
- Post count include original post

Thus some queries needed to be changed and the template no longer needs to add 1 to the post count.

### CODE REVIEW

**Comment by automaciej** [comment]
Hi Zeta, 

This looks like a change that would make the script work with phpBB 3.1/3.2, but would prevent it from working with phpBB 3.0. In my case, the reason why I decided to archive a phpBB forum was that I was unable to upgrade from 3.0 to 3.1. Support for 3.0 is vital for this tool.

Would you care to make the change such that it works with both versions? If not, we could just make a separate git branch for phpBB 3.1. What do you think?

**Comment by ZetaTwo** [comment]
Hi!

Totally understand the need to keep it 3.0 compatible. I can make a version that works with both. Either auto-detect or, maybe just add a config value. I'll get back with a new version when I have some time over. Will probably be in a few weeks or so since I'm a little bit overburdened ATM.

**Comment by ZetaTwo** [comment]
It's not beautiful. There's some repetition which can be optimized away but I didn't really have time to polish it and it works.

**Review by automaciej — APPROVED** [review]
That's good enough. Thanks!

**Pull request merged**
