### PR TITLE
PHP 7.0

### PR DESCRIPTION
**Pull request by automaciej**
Hi!

I've made a couple edits to run the converter with PHP 7.0. This pull requests changes a number of things, but each change is in a dedicated commit.

- Convert README to Markdown
- Use long opening tag (<?php … >) so it works out of the box, otherwise "php convert.php" just prints the code to the screen
- Use HTML_BBCodeParser2 (which is the current variant of the bbcode parsing library as of 2016)
- Tolerate a symlink 'static', not only a directory (I wanted to run under ~/src/… but output to ~/public_html/… using a symlink)
- Use PDO for MySQL queries, because PHP 7.0 no longer has the mysql_* functions.
- Minor fixes in templates
- Wrap top-level function calls in a try-catch block, which allows printing a helpful error message.

I hope that it's okay to bundle them all together in one pull request.

Maciej

### CODE REVIEW

**Comment by groovecoder** [comment]
Hi, thanks for the contribution. I haven't actually touched this code since back in 2011. I'd be happy to transfer this repo to you for any ongoing maintenance you'd like to do?

**Comment by automaciej** [comment]
Hi! That works for me. I have a more changes lined up, and having a free hand will be useful. Thanks!

**Comment by groovecoder** [comment]
Looks like you'll have to delete your fork before I can transfer to you. So I'll go ahead and merge this PR so you can delete your fork without losing this PR. Let me know when you've deleted your fork and I'll transfer.

**Comment by automaciej** [comment]
Done! My fork is now gone.

**Comment by groovecoder** [comment]
Started the transfer. Think you need to approve it?

**Comment by automaciej** [comment]
I don't see anything, no notifications, no emails... What should I see?

**Comment by automaciej** [comment]
OK! I got the email. It's done, thank you!

**Pull request merged**
